import React from 'react'
import NewsArticle from './NewsArticle'
import './style.css'

function App() {
    return (
        <div className="container">
            <NewsArticle newsTitle="Man Obsessed With Cat Rescue Transforms Home into Feline Playland; And You Can Too (For Charity)" newsAuthor="By McKinley Corbley" newsSummary="If someone is renovating their home, it usually consists of something like redoing their bathroom or installing new kitchen counters – not transforming their house into a wondrous cat playland. Nevertheless, that is exactly what Peter Cohen did with his home in Santa Barbara, California." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/Cat-on-Spiral-Pillar-Houzz-Youtube-Screenshot.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/man-transforms-home-into-feline-playland-and-you-can-too/" />
            <NewsArticle newsTitle="Taxing Empty Apartments Could Be the Solution to Affordable Housing in Expensive Cities, New Study Says" newsAuthor="By Good News Network" newsSummary="Rather than building new homes to help satisfy housing markets, this fascinating new study says that taxing empty homes in developed cities could increase housing affordability for local residents while simultaneously generating income for municipal governments." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/London-Apartments-CC-Beyond-My-Ken-via-WIkipedia-Commons.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/empty-homes-tax-study-in-uk/" />
            <NewsArticle newsTitle="Cheap 2D Material Can Cleanse 99.9999% of Bacteria From Water in 30 Minutes Simply by Using the Sun" newsAuthor="By McKinley Corbley" newsSummary="This latest scientific breakthrough from China could bring cheap, clean drinking water to people around the world. Earlier this month, scientists from Yangzhou University developed a water system that used sunlight and 2D materials to purify water of 99.9999% of bacteria – including E. coli. According to their tests, their eco-friendly system was able to purify enough daily drinking water for four people in just under 30 minutes." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2016/03/glasses-of-water-Sun-Star-permission.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/2d-material-uses-sunlight-to-clean-water-in-30-minutes/" />
            <NewsArticle newsTitle="When Parents Accidentally Lock Keys in Their Car With Infant Daughter, Group of Inmates Offer Their Skills" newsAuthor="By McKinley Corbley" newsSummary="Though it may seem counterintuitive, these prison inmates were being cheered on by a crowd of spectators as they were breaking into a couple’s car earlier this week. However, the inmates weren’t forcing their way into the SUV for any nefarious purposes; they were simply trying to reunite a 1-year-old girl with her parents." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/New-Port-Richey-Inmates-Shadow-Lantry-Facebook-Screenshot.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/parents-accidentally-lock-keys-in-car-with-infant-when-inmates-offer-help/" />
            <NewsArticle newsTitle="These Floating Trashcans Are Being Deployed Around the World So They Can Suck Up Tons of Ocean Trash" newsAuthor="By McKinley Corbley" newsSummary="After facilitating a successful crowdfunding campaign in 2016, a floating vacuum for ocean pollution is sucking up hundreds of pounds of litter around the world. The Seabin is an ocean trashcan that tidies up marinas, bays, and bodies of water by sucking up rubbish from the surrounding area. The device can collect up to 44 pounds (20 kilograms) of trash, including tiny plastic microbeads that are 2 millimeters small." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/Floating-Seabin-Seabin-Website-Released.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/seabins-being-internationally-deployed-to-suck-up-ocean-trash/" />
            <NewsArticle newsTitle="MOTH Monday: ‘Something Really Good Will Come From This’" newsAuthor="By Good News Network" newsSummary="Today is MOTH Monday on Good News Network: In partnership with The Moth, a nonprofit dedicated to the art of storytelling, we bring you the most uplifting speakers from live stages across the world. Denise Scheuermann took the stage in Pittsburgh, Pennsylvania to tell the audience about a ritual of hope that she always used throughout her medical career. Something really good will come from this." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/moth-monday-graphic-microphone-1024x480.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/moth-monday-something-good-mantra/" />
            <NewsArticle newsTitle="‘Guardian’ Officer Has Saved Over 200 People From Jumping Off the Golden Gate Bridge" newsAuthor="By McKinley Corbley" newsSummary="It’s a police officer’s job to protect and serve – but Kevin Briggs never thought that his job would lead him to save over 200 people from committing suicide. Briggs has been dubbed the “Guardian of the Golden Gate Bridge” because of his awe-inspiring history of talking people down from the edge of the historic landmark." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/Kevin-Briggs-and-Golden-Gate-Bridge-Released.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/guardian-officer-has-saved-over-200-people-from-jumping-off-the-golden-gate-bridge/" />
            <NewsArticle newsTitle="New ‘Trojan Horse’ Cancer Drug Successfully Treats Patients With 6 Different Kinds of Lethal Tumors" newsAuthor="By Good News Network" newsSummary="A brand new type of cancer drug that acts as a “Trojan horse” to get inside tumor cells has shown promise in patients with advanced, drug-resistant cancers. Patients with six different cancer types, including those with cervical, bladder, ovarian and lung tumors, have responded positively to the new treatment." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/Cervical-Cancer-Cells-National-Cancer-Institute-CC-via-Wikipedia-Commons.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/trojan-horse-drug-treats-patients-with-6-kinds-of-cancer/" />
            <NewsArticle newsTitle="In Historic Announcement, the World Health Organization (WHO) Proposes Removing Cannabis From Most Dangerous Drug Category" newsAuthor="By McKinley Corbley" newsSummary="Following a lengthy review process, international opponents of the ‘war on drugs’ are applauding the World Health Organization (WHO) move toward removing cannabis from its placement in the drug category reserved for the most dangerous substances. Currently, whole-plant marijuana and cannabis resin are considered a schedule IV substance, indicating that any medical uses for the substance are outweighed by their potential for abuse. The scheduling was originally created in 1961 by a United Nations treaty on ‘Narcotic Drugs,’ as a means of setting an international framework for medical research, trade, and legislation." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/01/Cannabis-sativa-hemp-plant-cc-kat_geb.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/un-proposes-removing-cannabis-from-most-dangerous-drug-category/" />
            <NewsArticle newsTitle="This 2-Year-Old Deaf Girl Loves People – So Her Whole Neighborhood is Learning Sign Language" newsAuthor="By Good News Network" newsSummary="Hearing impairment can often serve as a social barrier for those who don’t know how to speak sign language – but in this little Massachusetts town, sign language has actually brought the community together. 2-year-old Samantha Savitz is deaf, but that doesn’t stop her from being an outgoing little toddler. Whenever Samantha is out with her parents in their town of Newton, she tries to chat up everyone she meets." newsImage="https://www.goodnewsnetwork.org/wp-content/uploads/2019/02/Samantha-Savitz-and-Neighbors-CBS-News-Screenshot.jpg" newsColor="slate-gray" newsURL="https://www.goodnewsnetwork.org/neighborhood-learns-sign-language-for-deaf-toddler/" />
        </div>
    )
}

export default App